export const ADD_USER_BY_ADMIN = 'ADD_USER_BY_ADMIN';
export const ADD_ALLCODE = 'ADD_ALLCODE';
export const ADD_PRICE = 'ADD_PRICE';

export const LOG_OUT ='LOG_OUT';


export const FETCH_USERS_LOGIN = 'FETCH_USERS_LOGIN';
export const ADD_USER_LOGIN = 'ADD_USER_LOGIN';
export const UPDATE_USERS_LOGIN = 'UPDATE_USERS_LOGIN';
export const DELETE_USERS_LOGIN = 'DELETE_USERS_LOGIN';
export const ADD_USER_FROM_TABLE='ADD_USER_FROM_TABLE';

export const ADD_ALL_DOCTORS = 'ADD_ALL_DOCTORS';
export const ADD_OUTSTANDING_DOCTORS ='ADD_OUTSTANDING_DOCTORS';
export const ADD_SELECTED_DOCTOR = 'ADD_SELECTED_DOCTOR';

export const FETCH_ALLCODE_SCHEDULE_TIME ='FETCH_ALLCODE_SCHEDULE_TIME'

export const dateFormat = {
    SEND_TO_SERVER:'YYYY-MM-DD'
};

export const GET_DETAIL_DOCTOR = 'GET_DETAIL_DOCTOR';
export const USER_ROLE={
    ADMIN:'R1',
    DOCTOR:'R2',
    PATIENT:'R3'
}

export const CRUD_ACTION  = {
    CREATE:"CREATE",
    EDIT:'EDIT',
    DELETE:"DELETE",
    READ:"READ"
}


